---
- hosts: archlinux
  vars_prompt:
    - name: filename
      prompt: "Nom du fichier?"
      private: no
    - name: hello
      prompt: "Message?"

  handlers:
    - name: Read file
      command: "cat /tmp/{{ filename }}"
      register: file_content
    - name: Print file content
      debug:
        var: file_content.stdout

  tasks:
    - name: Print IP address
      debug:
        var: ansible_facts.all_ipv4_addresses[0]
    - name: Print hello
      debug:
        var: hello
    - name: Print filename
      debug:
        var: filename
    - name: Copy bonjour file
      template:
        src: bonjour_var.j2
        dest: "/tmp/{{ filename }}"
      notify:
        - Read file
        - Print file content
