all:
  hosts:
    arch1:
    arch2:
  children:
    webserver:
      hosts:
        arch1:
      vars:
        hello: "I am a webserver"
    load-balancer:
      hosts:
        arch2:
    archlinux:
      hosts:
        arch1:
        arch2:
      vars:
        filename: "hello.archlinux"

